# Generated by Django 4.2.5 on 2023-10-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Date_added',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='Phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
