# Generated by Django 4.2.5 on 2023-10-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_member_date_added_member_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Phone_number',
            new_name='Phone',
        ),
    ]
